name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

permissions:
  contents: write  # Allows pushing changes to the repository

jobs:
  test:  #test before deployed 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install  # Install necessary packages

      - name: Run Tests
        run: npm test  # Run the test cases before deployment

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures deployment only runs if tests pass
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .  # Deploy the root folder
