name: pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Use a more stable version if necessary

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgconf-2-4  # Install the missing package
        pip install -r requirements.txt  # Install the Python dependencies

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q
